version: "3.8"

services:
  nextjs:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - nextjs-dev-node_modules:/app/node_modules
      - nextjs-dev-next:/app/.next
    restart: always

  frontend:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - nextjs
    restart: always

volumes:
  nextjs-dev-node_modules:
  nextjs-dev-next:
